/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as ItemCategoriesRouteImport } from './routes/item-categories'
import { Route as InventoryPolicyRouteImport } from './routes/inventory-policy'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemCategoriesRoute = ItemCategoriesRouteImport.update({
  id: '/item-categories',
  path: '/item-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryPolicyRoute = InventoryPolicyRouteImport.update({
  id: '/inventory-policy',
  path: '/inventory-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/inventory-policy': typeof InventoryPolicyRoute
  '/item-categories': typeof ItemCategoriesRoute
  '/items': typeof ItemsRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/inventory-policy': typeof InventoryPolicyRoute
  '/item-categories': typeof ItemCategoriesRoute
  '/items': typeof ItemsRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/inventory-policy': typeof InventoryPolicyRoute
  '/item-categories': typeof ItemCategoriesRoute
  '/items': typeof ItemsRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/inventory-policy'
    | '/item-categories'
    | '/items'
    | '/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/inventory-policy'
    | '/item-categories'
    | '/items'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/inventory-policy'
    | '/item-categories'
    | '/items'
    | '/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  InventoryPolicyRoute: typeof InventoryPolicyRoute
  ItemCategoriesRoute: typeof ItemCategoriesRoute
  ItemsRoute: typeof ItemsRoute
  WarehousesRoute: typeof WarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-categories': {
      id: '/item-categories'
      path: '/item-categories'
      fullPath: '/item-categories'
      preLoaderRoute: typeof ItemCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-policy': {
      id: '/inventory-policy'
      path: '/inventory-policy'
      fullPath: '/inventory-policy'
      preLoaderRoute: typeof InventoryPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  InventoryPolicyRoute: InventoryPolicyRoute,
  ItemCategoriesRoute: ItemCategoriesRoute,
  ItemsRoute: ItemsRoute,
  WarehousesRoute: WarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
